default:
  image:
    name: rust:latest
  cache:
    key: "$CI_JOB_NAME---$CI_COMMIT_REF_SLUG"
    paths:
      - .cargo/bin
      - .cargo/registry/index
      - .cargo/registry/cache
      - target/debug/deps
      - target/debug/build
      - .cache-info
    policy: pull-push

variables:
  CARGO_HOME: ${CI_PROJECT_DIR}/.cargo

stages:
  - test

lint:
  stage: test
  before_script:
    - ./.gitlab-cargo-cache-expire.sh
  script:
    - rustup component add clippy rustfmt
    - cargo clippy --workspace --all-targets --features full-test-suite
    - cargo clippy --workspace --all-targets --features full-test-suite,forbid-unsafe
    - cargo clippy --workspace --all-targets --features full-test-suite --no-default-features
    - cargo clippy --workspace --all-targets --no-default-features
    - cargo fmt --all --check

# modern rust
test:
  stage: test
  before_script:
    - ./.gitlab-cargo-cache-expire.sh
  script:
    - cargo test --workspace --all-targets --features full-test-suite
    - cargo test --workspace --doc         --features full-test-suite
    - cargo test --workspace --all-targets --features full-test-suite,forbid-unsafe
    - cargo test --workspace --doc         --features full-test-suite,forbid-unsafe
    - cargo test --workspace --all-targets --features full-test-suite --no-default-features
    - cargo test --workspace --doc         --features full-test-suite --no-default-features
    - cargo test --workspace --all-targets --no-default-features
    - cargo test --workspace --doc         --no-default-features
    - cargo test --workspace --all-targets --features test-suite-extra --no-default-features
    - ./test-ancient-hashbrown.sh

# oldest version of rust that supports all features
test-old:
  image: rust:1.70
  stage: test
  before_script:
    - ./.gitlab-cargo-cache-expire.sh
    - ./msrv-lock.sh
  script:
    - cargo test --workspace --all-targets --features full-test-suite
    - cargo test --workspace --doc         --features full-test-suite
    - cargo test --workspace --all-targets --features full-test-suite,forbid-unsafe
    - cargo test --workspace --doc         --features full-test-suite,forbid-unsafe
    - cargo test --workspace --all-targets --features full-test-suite --no-default-features
    - cargo test --workspace --doc         --features full-test-suite --no-default-features
    - cargo test --workspace --all-targets --no-default-features
    - cargo test --workspace --doc         --no-default-features
    - cargo test --workspace --all-targets --features test-suite-extra --no-default-features
    - ./test-ancient-hashbrown.sh

# oldest supported version of rust
test-msrv:
  image: rust:1.68
  stage: test
  before_script:
    - ./.gitlab-cargo-cache-expire.sh
    - ./msrv-lock.sh
  script:
    - export CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse
    - cargo test --workspace --all-targets --features msrv-test-suite
    - cargo test --workspace --doc         --features msrv-test-suite
    - cargo test --workspace --all-targets --features msrv-test-suite,forbid-unsafe
    - cargo test --workspace --doc         --features msrv-test-suite,forbid-unsafe
    - cargo test --workspace --all-targets --features msrv-test-suite --no-default-features
    - cargo test --workspace --doc         --features msrv-test-suite --no-default-features
    - cargo test --workspace --all-targets --no-default-features
    - cargo test --workspace --doc         --no-default-features
    - cargo test --workspace --all-targets --features test-suite-extra --no-default-features
    - ./test-ancient-hashbrown.sh
