default:
  image:
    name: rust:latest
  cache:
    key: "$CI_JOB_NAME---$CI_COMMIT_REF_SLUG"
    paths:
      - .cargo/bin
      - .cargo/registry/index
      - .cargo/registry/cache
      - target/debug/deps
      - target/debug/build
      - .cache-info
    policy: pull-push

variables:
  CARGO_HOME: ${CI_PROJECT_DIR}/.cargo

stages:
  - test

lint:
  stage: test
  script:
    - ./.gitlab-cargo-cache-expire.sh
    - rustup component add clippy rustfmt
    - cargo clippy --workspace --all-targets --features full-test-suite
    - cargo clippy --workspace --all-targets --features full-test-suite --no-default-features
    - cargo clippy --workspace --all-targets --no-default-features
    - cargo fmt --all --check

test:
  stage: test
  script:
    - ./.gitlab-cargo-cache-expire.sh
    - cargo test --workspace --all-targets --features full-test-suite
    - cargo test --workspace --doc         --features full-test-suite
    - cargo test --workspace --all-targets --features full-test-suite --no-default-features
    - cargo test --workspace --doc         --features full-test-suite --no-default-features
    - cargo test --workspace --all-targets --no-default-features
    - cargo test --workspace --doc         --no-default-features
    - cargo test --workspace --all-targets --features test-suite-extra --no-default-features
    - ./test-ancient-hashbrown.sh

test-msrv:
  image: rust:1.65
  stage: test
  before_script:
    - ./downgrade-for-msrv.sh
  script:
    - ./.gitlab-cargo-cache-expire.sh
    - cargo test --workspace --all-targets --features full-test-suite
    - cargo test --workspace --doc         --features full-test-suite
    - cargo test --workspace --all-targets --features full-test-suite --no-default-features
    - cargo test --workspace --doc         --features full-test-suite --no-default-features
    - cargo test --workspace --all-targets --no-default-features
    - cargo test --workspace --doc         --no-default-features
    - cargo test --workspace --all-targets --features test-suite-extra --no-default-features
    - ./test-ancient-hashbrown.sh
