[package]
name = "fuzz-libfuzzer"
version = "0.0.0"
authors = [
    "Kent Ross <k@mad.cash>",
]
publish = false
edition = "2021"
default-run = "bilrost_fuzz"

[workspace]
members = [
    "afl",
    "common",
]

[package.metadata]
cargo-fuzz = true

[dependencies]
common = { path = "common" }
libfuzzer-sys = "0.4"

[features]
forbid-unsafe = ["common/forbid-unsafe"]
extra = ["common/extra"]

[[bin]]
name = "bilrost_fuzz"
path = "fuzzers/bilrost_fuzz.rs"

[[bin]]
name = "bilrost_fuzz_message_via_oneof"
path = "fuzzers/bilrost_fuzz_message_via_oneof.rs"

[[bin]]
name = "bilrost_borrowed_fuzz"
path = "fuzzers/bilrost_borrowed_fuzz.rs"
required-features = ["common/compare-borrowed"]

[[bin]]
name = "bilrost_type_support_fuzz"
path = "fuzzers/bilrost_type_support_fuzz.rs"

[[bin]]
name = "parse_date_fuzz"
path = "fuzzers/parse_date_fuzz.rs"
