[package]
name = "test-types"
version = "0.0.0"
publish = false
edition.workspace = true

[dependencies]
bilrost = { path = "..", default-features = false, features = [
    "auto-optimize",
    "bstr",
    "bytestring",
    "chrono",
    "derive",
    "jiff",
    "no-recursion-limit",
    "smol_str",
    "std",
    "time",
    "tinyvec",
] }
bilrost-types = { path = "../bilrost-types" }
bstr = "1.10"
bytes = "1"
bytestring = "1.3.1"
chrono = "0.4.34"
jiff = "0.2.35"
smol_str = { version = ">=0.1.24,<0.4", default-features = false }
time = "0.3.22"
tinyvec = "1"

[features]
test-suite-extra = []
