[package]
name = "common"
version = "0.0.0"
authors = [
    "Kent Ross <k@mad.cash>",
    "Dan Burkert <dan@danburkert.com>",
    "Tokio Contributors <team@tokio.rs>",
]
publish = false
edition = "2021"
resolver = "2"
default-run = "reproduce"

[package.metadata]
cargo-fuzz = true

[dependencies]
bilrost-types = { path = "../../bilrost-types" }
bstr = "1.10"
bytes = "1"
bytestring = "1.3.1"
chrono = "0.4.34"
eyre = "0.6.12"
once_cell = "1.20.2"
regex = "1.12.4"
time = "0.3"
tinyvec = "1"

[dependencies.bilrost]
path = "../.."
default-features = false
features = [
    "bstr",
    "bytestring",
    "derive",
    "auto-optimize",
    "no-recursion-limit",
    "chrono",
    "std",
    "time",
    "tinyvec",
]

[features]
compare-borrowed = []
# this is the feature name we enable everywhere for the workspace test suite, ensuring that we will
# assert all our types' borrowing impls via the test messages.
full-test-suite = ["compare-borrowed"]

[[bin]]
name = "reproduce"

[[bin]]
name = "reproduce_parse_date"
