[package]
name = "common"
version = "0.0.0"
authors = [
    "Kent Ross <k@mad.cash>",
    "Dan Burkert <dan@danburkert.com>",
    "Tokio Contributors <team@tokio.rs>",
]
publish = false
edition = "2021"
default-run = "reproduce"

[package.metadata]
cargo-fuzz = true

[dependencies]
bilrost-types = { path = "../../bilrost-types" }
bstr = "1.11"
bytes = "1"
chrono = "0.4"
eyre = "0.6"
regex = "1.11"
time = "0.3"
tinyvec = "1"

[dependencies.bilrost]
path = "../.."
default-features = false
features = [
    "derive",
    "auto-optimize",
    "no-recursion-limit",
    "chrono",
    "std",
    "time",
    "tinyvec",
]

[[bin]]
name = "reproduce"

[[bin]]
name = "reproduce_parse_date"
