[package]
name = "common"
version = "0.0.0"
authors = [
    "Kent Ross <k@mad.cash>",
]
publish = false
edition = "2021"
resolver = "2"
default-run = "reproduce"

[package.metadata]
cargo-fuzz = true

[dependencies]
bilrost = { path = "../..", default-features = false }
bilrost-types = { path = "../../crate-types" }
bytes = "1"
chrono = "0.4.34"
eyre = "0.6.12"
once_cell = "1.20.2"
regex = "1.12.4"
test-types = { path = "../../test-types" }

[features]
compare-borrowed = []
forbid-unsafe = ["bilrost/forbid-unsafe"]
# these are the feature names we enable everywhere for the workspace test suite, ensuring that we
# will assert all our types' borrowing impls via the test messages.
msrv-test-suite = ["compare-borrowed"]
full-test-suite = ["msrv-test-suite", "test-types/full-type-support"]
extra = ["bilrost/test-suite-extra"]

[[bin]]
name = "reproduce"

[[bin]]
name = "reproduce_parse_date"
