[package]
name = "bilrost-derive"
version.workspace = true
authors = [
    "Kent Ross <k@mad.cash>",
    "Dan Burkert <dan@danburkert.com>",
    "Lucio Franco <luciofranco14@gmail.com>",
    "Tokio Contributors <team@tokio.rs>",
]
license = "Apache-2.0"
repository = "https://github.com/mumbleskates/bilrost"
documentation = "https://docs.rs/bilrost-derive"
readme = "README.md"
description = "A compact protobuf-like serializer and deserializer for the Rust Language."
edition.workspace = true
rust-version.workspace = true

[lib]
proc-macro = true

[dependencies]
eyre = "0.6.12"
itertools = { version = "0.15", default-features = false, features = ["use_alloc"] }
proc-macro2 = "1"
quote = "1"
syn = { version = ">=2,<4", features = ["extra-traits", "full"] }
